volumes:
  pg_data_production:
  backend_static:
  frontend_static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    restart: always
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: 33bot/taski_backend
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - backend_static:/app/collected_static

  frontend:
    image: 33bot/taski_fronted 
    env_file: .env
    restart: always
    command: >
      sh -c "cp -r /app/build/. /frontend_static/ && nginx -g 'daemon off;'"
    volumes:
      - frontend_static:/frontend_static

  gateway:
    image: 33bot/taski_gateway
    env_file: .env
    restart: always
    depends_on:
      - backend
      - frontend
    volumes:
      - backend_static:/static
      - frontend_static:/frontend_static
    ports:
      - "8000:80"
