server {
    listen 80;
    server_name 33taski3.freedynamicdns.org;

    location /static/admin/ {
        alias /backend_static/admin/;
    }

    location /static/rest_framework/ {
        alias /backend_static/rest_framework/;
    }

    location /static/ {
        alias /frontend_static/static/;
    }

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    location / {
        root /frontend_static;
        index index.html;
        try_files $uri /index.html;
    }
}
